name: Norminette and Build
on: [push, pull_request]

jobs:
  norminette:
    name: Norminette
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: alexandregv/norminette-action@v3
  build:
      name: Build
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
          with:
            submodules: true
        - name: make
          run: make
